//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pit4Casus.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FilmSet()
        {
            this.BeoordelingSet = new HashSet<BeoordelingSet>();
            this.FilmpersoneelSet = new HashSet<FilmpersoneelSet>();
            this.PersoonlijkeLijstSet = new HashSet<PersoonlijkeLijstSet>();
        }
    
        public int FilmID { get; set; }
        public Nullable<int> FilmInspiratieID { get; set; }
        public string FilmRemake { get; set; }
        public bool FilmKleur { get; set; }
        public int FilmJaar { get; set; }
        public string FilmTaal { get; set; }
        public int FilmDuur { get; set; }
        public string FilmNaam { get; set; }
        public int FilmGenre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeoordelingSet> BeoordelingSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmpersoneelSet> FilmpersoneelSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersoonlijkeLijstSet> PersoonlijkeLijstSet { get; set; }
    }
}
