//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pit4Casus.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmpersoneelSet
    {
        public int FilmpersoneelID { get; set; }
        public int FilmFilmID { get; set; }
        public int PersoneelPersoneelID { get; set; }
        public string KarakterNaam { get; set; }
        public string FunctieNaam { get; set; }
    
        public virtual FilmSet FilmSet { get; set; }
        public virtual PersoneelSet PersoneelSet { get; set; }
    }
}
