//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pit4Casus.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class GebruikerSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GebruikerSet()
        {
            this.BeoordelingSet = new HashSet<BeoordelingSet>();
            this.PersoonlijkeLijstSet = new HashSet<PersoonlijkeLijstSet>();
        }
    
        public int GebruikerID { get; set; }
        public string GebruikerNaam { get; set; }
        public string GebruikerWachtwoord { get; set; }
        public bool GebruikerFunctie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeoordelingSet> BeoordelingSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersoonlijkeLijstSet> PersoonlijkeLijstSet { get; set; }
    }
}
