//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pit4Casus.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersoneelSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersoneelSet()
        {
            this.FilmpersoneelSet = new HashSet<FilmpersoneelSet>();
        }
    
        public int PersoneelID { get; set; }
        public string PersoneelNaam { get; set; }
        public System.DateTime PersoneelGebDatum { get; set; }
        public bool PersoneelGeslacht { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmpersoneelSet> FilmpersoneelSet { get; set; }
    }
}
